title: Kari's GitHub Webpage
author: GitHub User
email: kari0219@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kari's page for side projects

# social links
twitter_username: your-twitter-handle
github_username:  kar0219

show_excerpts: true # set to false to remove excerpts on the homepage
